name: CLA

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - reopened
      - opened
      - synchronize

jobs:
  check:
    if: >-
      !github.event.repository.fork
      && (
        github.event.comment.body == '@conda-bot check'
        || github.event_name == 'pull_request_target'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Check CLA
        uses: conda/actions/check-cla@customize-cla-repo
        with:
          token: ${{ secrets.TCC-TOKEN }}
          label: cla-signed

          cla_repo: kenodegard/test-check-cla
          cla_token: ${{ secrets.TCC-CLA_TOKEN}}
          cla_path: .github/cla-config.yml
