name: Check CLA

on:
  issue_comment:
    types:
      - created
  pull_request_target:

jobs:
  check:
    if: >-
      !github.event.repository.fork
      && (
        github.event.comment.body == '@conda-bot check'
        && github.event.issue.pull_request
        || github.event_name == 'pull_request_target'
      )
    runs-on: ubuntu-latest
    # permissions:
    #   pull-requests: write
    #   statuses: write
    steps:
      - uses: conda/actions/check-cla@customize-cla-repo
        with:
          token: ${{ secrets.ALL_COMMENTS_LABELS_STATUSES_TOKEN }}
          label: cla-signed

          cla_repo: kenodegard-org/test-check-cla
          cla_path: .github/cla-config.yml

          cla_fork: kenodegard-bot/test-check-cla
          cla_token: ${{ secrets.TCC_CREATE_PR_TOKEN }}
